apiVersion: v1
kind: ConfigMap
metadata:
  name: redirects
data: !Index
  over: !Var redirects
  as: redirect
  by: !Format "{redirect.hosts[0]}.conf"
  template: !With
    vars:
      server_name: !Join
        items: !Lookup redirect.hosts
        separator: " "
    template: !If
      test: !Lookup redirect.pass_path
      then: !Format |
        server {{
          listen 80;
          server_name {server_name};
          return 302 {redirect.target}$request_uri;
        }}
      else: !Format |
        server {{
          listen 80;
          server_name {server_name};
          return 302 {redirect.target};
        }}
