on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'      
      - uses: pairity/setup-cd-tools@30acb848f9ff747aff4810dac40c5cc0971f485d
        with:
          kubectl: '1.20.4'
          skaffold: '1.20.0'         
      - run: python3 -m pip install emskaffolden
      - run: emskaffolden -E production -- deploy -n redirects
