on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'      
      - uses: azure/setup-kubectl@v1
      - run: python3 -m pip install emskaffolden && emskaffolden -E production
      - run: kubectl apply -f kubernetes/template.compiled.yaml -n redirects
