on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'      
      - run: python3 -m pip install emskaffolden && emskaffolden -E production
      - run: env
      - uses: azure/k8s-set-context@v1
        with:
          method: service-account    
      - uses: Azure/k8s-deploy@v1.4
        with:
          namespace: redirects
          manifests: |
            kubernetes/template.compiled.yaml
          kubectl-version: '1.20.4'