on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: con2/emskaffolden-action@main
        with:
          args: deploy -E production -- -n redirects